"""add style and key in score table

Revision ID: de41477eff84
Revises: d307da553f07
Create Date: 2026-02-17 12:54:36.238606

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel.sql import sqltypes

# revision identifiers, used by Alembic.
revision: str = "de41477eff84"
down_revision: Union[str, Sequence[str], None] = "d307da553f07"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("imslp", sa.Column("style", sqltypes.AutoString(), nullable=False))
    op.add_column("imslp", sa.Column("key", sqltypes.AutoString(), nullable=False))
    op.add_column("score", sa.Column("style", sqltypes.AutoString(), nullable=False))
    op.add_column("score", sa.Column("key", sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("score", "key")
    op.drop_column("score", "style")
    op.drop_column("imslp", "key")
    op.drop_column("imslp", "style")
    # ### end Alembic commands ###
